version: '3.7'

services:
  api:
    build: .
    volumes:
      - ./:/app
    command: gunicorn application:application -b :8080 --worker-class aiohttp.GunicornWebWorker --workers=12 --reload --access-logfile -
    ports:
      - "9000:8080"

  frontend:
    build: ./frontend
    volumes:
      - ./:/app
    command: npm start
    ports:
      - "9090:3000"